name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: |
          pip install pytest
          pip install numpy

      - name: BlasLapack-1 Test
        id: blaslapack1
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: BlasLapack1
          command: cd BlasLapack-1 && bash run_test.sh
          timeout: 20
          max-score: 1

      - name: BlasLapack-2 Test
        id: blaslapack2
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: BlasLapack2
          command: cd BlasLapack-2 && bash run_test.sh
          timeout: 20
          max-score: 1

      - name: EigenExercise
        id: eigenexercise
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: EigenExercise
          command: cd EigenExercise && bash run_test.sh
          timeout: 20
          max-score: 1
    
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          BLASLAPACK1_RESULTS: "${{steps.blaslapack1.outputs.result}}"
          BLASLAPACK2_RESULTS: "${{steps.blaslapack2.outputs.result}}"
          EIGENEXERCISE_RESULTS: "${{steps.eigenexercise.outputs.result}}"
        with:
          runners: blaslapack1,blaslapack2,eigenexercise 
